import type { WOD } from './types';

export const wods: WOD[] = [
  {
    id: '1',
    name: 'Murph',
    type: 'For Time',
    date: '2024-05-27',
    description: '1-mile run\n100 pull-ups\n200 push-ups\n300 squats\n1-mile run\n\nPartition the pull-ups, push-ups, and squats as needed. Start and finish with a mile run. If you\'ve got a 20-lb. vest or body armor, wear it.',
    result: '45:32',
    imageUrl: 'https://picsum.photos/seed/murph/600/400',
    imageHint: 'man running',
  },
  {
    id: '2',
    name: 'Cindy',
    type: 'AMRAP',
    date: '2024-06-10',
    description: '5 pull-ups\n10 push-ups\n15 squats',
    duration: 20,
    result: '23 Rounds + 5 pull-ups',
    imageUrl: 'https://picsum.photos/seed/cindy/600/400',
    imageHint: 'woman pull-up',
  },
  {
    id: '3',
    name: 'Fran',
    type: 'For Time',
    date: '2024-06-15',
    description: '21-15-9 reps of:\n- Thrusters (95/65 lb)\n- Pull-ups',
    result: '03:45',
    imageUrl: 'https://picsum.photos/seed/fran/600/400',
    imageHint: 'barbell gym',
  },
  {
    id: '4',
    name: 'Death by Burpees',
    type: 'EMOM',
    date: '2024-06-20',
    description: 'Minute 1: 1 Burpee\nMinute 2: 2 Burpees\nMinute 3: 3 Burpees\n...and so on, until you cannot complete the required number of burpees in the minute.',
    rounds: 18,
    result: '17 Rounds',
    imageUrl: 'https://picsum.photos/seed/burpee/600/400',
    imageHint: 'person tired',
  },
  {
    id: '5',
    name: 'Tabata Something Else',
    type: 'Tabata',
    date: '2024-06-22',
    description: 'Tabata Pull-ups\nTabata Push-ups\nTabata Sit-ups\nTabata Squats\n\nThe Tabata interval is 20 seconds of work followed by 10 seconds of rest for 8 intervals. Rest 1 minute between each exercise. Score is total reps.',
    result: '421 Reps',
    imageUrl: 'https://picsum.photos/seed/tabata/600/400',
    imageHint: 'stopwatch gym',
  },
];
